package azuread

import (
	"context"

	"github.com/turbot/steampipe-plugin-sdk/v5/grpc/proto"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin/transform"
)

func tableAzureAdDirectoryAuditReport(_ context.Context) *plugin.Table {
	return &plugin.Table{
		Name:        "azuread_directory_audit_report",
		Description: "Represents the list of audit logs generated by Azure Active Directory.",
		Get: &plugin.GetConfig{
			Hydrate: getGraphTable,
			IgnoreConfig: &plugin.IgnoreConfig{
				ShouldIgnoreErrorFunc: isIgnorableErrorPredicate([]string{"Request_ResourceNotFound", "Invalid object identifier"}),
			},
			KeyColumns: plugin.SingleColumn("id"),
		},
		List: &plugin.ListConfig{
			Hydrate: listGraphTable,
			KeyColumns: plugin.KeyColumnSlice{
				// Key fields
				{
					Name:      "activity_date_time",
					Require:   plugin.Optional,
					Operators: []string{">", ">=", "=", "<", "<="},
				},
				{
					Name:    "activity_display_name",
					Require: plugin.Optional,
				},
				{
					Name:    "category",
					Require: plugin.Optional,
				},
				{
					Name:    "correlation_id",
					Require: plugin.Optional,
				},
				{
					Name:    "filter",
					Require: plugin.Optional,
				},
				{
					Name:    "result",
					Require: plugin.Optional,
				},
			},
		},

		Columns: commonColumns([]*plugin.Column{
			{
				Name:        "id",
				Type:        proto.ColumnType_STRING,
				Description: "Indicates the unique ID for the activity.",
				Transform:   graphField("id"),
			},
			{
				Name:        "activity_date_time",
				Type:        proto.ColumnType_TIMESTAMP,
				Description: "Indicates the date and time the activity was performed.",
				Transform:   graphField("activityDateTime"),
			},
			{
				Name:        "activity_display_name",
				Type:        proto.ColumnType_STRING,
				Description: "Indicates the activity name or the operation name.",
				Transform:   graphField("activityDisplayName"),
			},
			{
				Name:        "category",
				Type:        proto.ColumnType_STRING,
				Description: "Indicates which resource category that's targeted by the activity.",
				Transform:   graphField("category"),
			},
			{
				Name:        "correlation_id",
				Type:        proto.ColumnType_STRING,
				Description: "Indicates a unique ID that helps correlate activities that span across various services. Can be used to trace logs across services.",
				Transform:   graphField("correlationId"),
			},
			{
				Name:        "logged_by_service",
				Type:        proto.ColumnType_STRING,
				Description: "Indicates information on which service initiated the activity (For example: Self-service Password Management, Core Directory, B2C, Invited Users, Microsoft Identity Manager, Privileged Identity Management.",
				Transform:   graphField("loggedByService"),
			},
			{
				Name:        "operation_type",
				Type:        proto.ColumnType_STRING,
				Description: "Indicates the type of operation that was performed. The possible values include but are not limited to the following: Add, Assign, Update, Unassign, and Delete.",
				Transform:   graphField("operationType"),
			},
			{
				Name:        "result",
				Type:        proto.ColumnType_STRING,
				Description: "Indicates the result of the activity. Possible values are: success, failure, timeout, unknownFutureValue.",
				Transform:   graphField("result"),
			},
			{
				Name:        "result_reason",
				Type:        proto.ColumnType_STRING,
				Description: "Indicates the reason for failure if the result is failure or timeout.",
				Transform:   graphField("resultReason"),
			},

			// JSON fields
			{
				Name:        "additional_details",
				Type:        proto.ColumnType_JSON,
				Description: "Indicates additional details on the activity.",
				Transform:   graphField("additionalDetails"),
			},
			{
				Name:        "initiated_by",
				Type:        proto.ColumnType_JSON,
				Description: "Indicates information about the user or app initiated the activity.",
				Transform:   graphField("initiatedBy"),
			},
			{
				Name:        "target_resources",
				Type:        proto.ColumnType_JSON,
				Description: "Indicates information on which resource was changed due to the activity. Target Resource Type can be User, Device, Directory, App, Role, Group, Policy or Other.",
				Transform:   graphField("targetResources"),
			},

			// Standard columns
			{
				Name:        "title",
				Type:        proto.ColumnType_STRING,
				Description: ColumnDescriptionTitle,
				Transform:   graphField("id"),
			},
			{
				Name:        "filter",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromQual("filter"),
				Description: "Odata query to search for directory audit reports.",
			},
		}),
	}
}
